### ISSUE TITLE
Throw error( java.lang.UnsatisfiedLinkError) in ai.djl.pytorch.jni.PyTorchLibrary.torchGetItem(long, long[]) 

### ISSUE THREAD

**Issue by cwjtojava** [deepjavalibrary/djl#1161]
No implementation found for long ai.djl.pytorch.jni.PyTorchLibrary.torchGetItem(long, long[]) (tried Java_ai_djl_pytorch_jni_PyTorchLibrary_torchGetItem and Java_ai_djl_pytorch_jni_PyTorchLibrary_torchGetItem__J_3J)

Simple:
static NDArray filterMatrix(NDArray matrix, int start) {
		Shape shape = matrix.getShape();
		long[] ss = new long[shape.dimension() - 1];
		for (int i = 0; i < ss.length; i++) {
			ss[i] = shape.get(i);
		}
		NDArray out = np.create(new Shape(ss));
		long a = ss[0];
		long b = ss[1];
		long c = ss[2];
		for (int i = 0; i < a; i++) {
			for (int j = 0; j < b; j++) {
				for (int k = 0; k < c; k++) {
					NDArray temp =  matrix.get(i, j, k);//throw the java.lang.UnsatisfiedLinkError
					out.set(new NDIndex(i, j, k), temp.get(start));
				}
			}
		}
		return out;
	}

...I hope to get your answer,Thanks.

**Comment by frankfliu** [comment]
@cwjtojava 
This most likely caused by JNI library mismatched with cached version. You machine cached an earlier version of snapshot JNI, and it doesn't match with latest code.

Would you please remove cache folder and try it again?

```
rm ~/.djl.ai/pytorch
```

If you are building from DJL source, you might also need clean pytorch engine project:
```
./gradlew :pytorch:pytorch-engine:clean
```

**Comment by frankfliu** [comment]
Feel free to reopen this issue if you still can reproduce it in latest version of DJL
