### ISSUE TITLE
Quick question anyways to make sure the system works in offline mode.

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [deepjavalibrary/djl#1197]
## Description

Just a quick question on offline reproducibility.
It is highly possible that it is possible to run model in offline mode.
However,how to make sure it works?
What should we make sure exist in the system is the key.
Of course,the basic will be javajdk,djl core api in jar or unpacked.
However for the recursive dependencies,it is kinda confusing some in user temp some in appdata.

Will this change the current api? How?
probably only related to networking ones in worse scenario.

Who will benefit from this enhancement?
everyone,stability,and decrease dependencies on network in runtime.

## References
sadly no?

**Comment by frankfliu** [comment]
1. For the dependencies, it should be fairly easy to include all jars that need for the project. Here is one example of you use gradle: You can declare your project use `application` plugin:

```
plugins {
    id 'application'
}
```

Then you have `gradle distZip` task, it will package all your dependencies into a zip file. And then you can distribute the zip file"

See: https://github.com/deepjavalibrary/djl/blob/master/examples/build.gradle#L2

2. I think you are talking to "*-native-auto" package that download the shared libraries at runtime. The "*-native-auto" is convenient if you don't know which platform (cpu/gpu, win/mac/linux) you are going to deploy to. If you know your target environment, you should use explicit dependency:

```
implemenation ai.djl.pytorch:pytorch-native-cpu:1.8.1:osx-x86_64
```

With explicit dependency, DJL won't download at runtime. You can even include multiple explicit dependencies in your project (we don't recommend you do it because those .jar file are very large, the GPU jar file can up to 1 GB).

Here is example for pytorch mac: https://docs.djl.ai/pytorch/pytorch-engine/index.html#macos

**Comment by xwaeaewcrhomesysplug** [comment]
noted i will try it in later.will close this issue first
