### ISSUE TITLE
NDArrayIndexer.set() always runs into UnsupportedOperationException on Boolean Index

### ISSUE THREAD

**Issue by ptrxwsmitt** [deepjavalibrary/djl#2424]
## Description
NDArrayIndexer.set() always runs into UnsupportedOperationException if fullSlice is null.
The actual set operation is called, as expected, but in any case the exception is called.

This is since the "return;" was removed with the following commit https://github.com/deepjavalibrary/djl/commit/a7ee40142241fa8a18f8f19148282b20b4578f6f#diff-e34afd51eb8b35f4ddca361974e0de00c77b0423fcbc20f94ccda9d5e4be9c4c  

Need to roll back to 0.17.0 now...

### Expected Behavior
return without exception.

### Error Message
UnsupportedOperationException:
"set() currently supports all, fixed and slices indices"

## How to Reproduce?
Run ndArray.set() with a boolean aray as index map 

## What have you tried to solve it?
Roll back to old version

**Comment by KexinFeng** [comment]
Thanks for reporting this issue and finding the relavant PR. However, I'm still somewhat confused about what you meant. 
1. "return;"  still exists in commit https://github.com/deepjavalibrary/djl/commit/a7ee40142241fa8a18f8f19148282b20b4578f6f#diff-e34afd51eb8b35f4ddca361974e0de00c77b0423fcbc20f94ccda9d5e4be9c4c
2. It is unclear about how to reproduce the error.

> `Run ndArray.set() with a boolean aray as index`
This will trigger Line110-Line116 in in commit https://github.com/deepjavalibrary/djl/commit/a7ee40142241fa8a18f8f19148282b20b4578f6f#diff-e34afd51eb8b35f4ddca361974e0de00c77b0423fcbc20f94ccda9d5e4be9c4c in NDArrayIndexer.java

If you could give more precise code to reproduce the issue, that would be helpful. 
Also, is your issue on MXNet rather than PyTorch?

**Comment by ptrxwsmitt** [comment]
Thanks for the support

1. Yes there is one 'return' for the (fullSlice != null) part., but no 'return' for the implicit else-part. 
2. Yes, Line110-Line116 will be triggered. That is right. :) 
But there is neither a return or an else-part.
Which means all cases will also trigger Line 123 (the Exception), too, after running 111 or 116 successfully.
This does not seem intended to me.

**Comment by KexinFeng** [comment]
Thanks for spotting this issue. It is solved now.
