### ISSUE TITLE
setTruncationStrategy fails with lowercase input

### ISSUE THREAD

**Issue by ux51ekac** [deepjavalibrary/djl#2540]
`setTruncationStrategy` seems to fail with the output of `getTruncationStrategy` due to a case mismatch.
For a tokenizer in use, `getTruncationStrategy` returns `longest_first`, however, `setTruncationStrategy` checks for uppercase values. The error message again shows lowercase, which is confusing.

https://github.com/deepjavalibrary/djl/blob/0d5098ca85457aa85061dc86d5cf8121fab84b20/extensions/tokenizers/rust/src/lib.rs#L666-L670

**Comment by siddvenk** [comment]
I'm assuming you are referring to `getTruncationStrategy` and `setTruncationStrategy`. Similar methods also exist for padding behavior, but none of these are exposed through the public Java API. On the Java side we do a case insensitive match on the strategy name, so there shouldn't be any issue. The error thrown here uses the lower case variants as those are what are documented in HuggingFace Tokenizer's python/rust documentation. The Upper Case comes from the default java enum behavior.

You shouldn't be calling these methods directly - they are the JNI methods we use to call the rust tokenizers implementation.

Are you running into an issue using the HuggingFaceTokenizer Java class? If so, can you provide a code sample that will let us reproduce and debug the issue?

**Comment by philipphutterer** [comment]
Of course you are right, I am referring to truncation, sorry for the confusion.

The problem is, I am trying to change the truncation strategy during runtime for an input that is not fed into a model directly (and reset it back afterwards). I could not find a way to change this with the Java interface, but maybe I am missing something?

Anyway, thanks for the help, I think for this exceptional case I just uppercase the output of `getTruncationStrategy`.

**Comment by siddvenk** [comment]
Currently the HuggingFaceTokenizer is Immutable. The truncation strategy cannot be changed after the tokenizer is created. 

Can you describe your use case a bit more? Would it be possible to create multiple tokenizers upfront with different strategies and use them at runtime? 

We can explore extending our interface to allow for using different padding/truncation behavior during tokenization

**Comment by ux51ekac** [comment]
> Can you describe your use case a bit more? Would it be possible to create multiple tokenizers upfront with different strategies and use them at runtime?

This is totally fine and I am doing this right now. Thanks for your help.

**Comment by siddvenk** [comment]
Great, I'm glad that will work for you. As @frankfliu mentioned it's important the Tokenizer is immutable for thread safety. I was hoping that the tokenizer rust library provided methods for specifying truncation/padding settings at tokenization time rather than just at creation time, but that doesn't seem to be the case.

Please repopen this issue if you have further questions.
