### ISSUE TITLE
UnsatisfiedLinkError: windows for Pytorch 1.3.1 

### ISSUE THREAD

**Issue by yingcuhk** [deepjavalibrary/djl#2731]
## Description

Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\.djl.ai\pytorch\1.13.1-cu117-win-x86_64\torch_cuda_cpp.dll: Can't find dependent libraries

I use DJL 0.23.0 and try to use it for interference in java. 

I have pytorch and cuda installed and can train pytorch model using local GPU. 

![L_H%L_K25)20EK7}9BZ7` I](https://github.com/deepjavalibrary/djl/assets/5819079/3b92a1df-3a70-4ef3-bc4f-25d271adb78a)

Do I need to use older version or how to solve this problem?

**Comment by frankfliu** [comment]
By default, DJL doesn't use the pytorch installed with Python. DJL will download PyTorch native library and save it in [cache folder](https://docs.djl.ai/docs/development/cache_management.html).

Your error usually caused by missing dependencies (or not included in path). You can use `dumpbin.exe` or dependency waller to check which library is missing on your system. see: https://docs.djl.ai/docs/development/troubleshooting.html#unsatisfiedlinkerror-issue
