### ISSUE TITLE
Avoid copying bundled ressources

### ISSUE THREAD

**Issue by StefanOltmann** [deepjavalibrary/djl#2952]
I want my app to function offline, so I included the engine as a JAR based on the tutorial, with my model contained within another JAR. This setup is working well thus far.

However, I observed that it still generates the `.djl.ai` directory containing the model inside a `cache` folder, and the PyTorch engine is extracted from the `pytorch-native-cpu-2.1.1-win-x86.jar` to `pytorch`.

It would be preferable to avoid writing these files, as they essentially double the space requirements for my app installation.

I'm unsure about the process, but the project at https://github.com/JetBrains/skiko managed to keep its `skiko-windows-x64.dll` alongside the JAR file, referencing them without copying. I believe a similar approach could be employed for the nine DLLs representing the PyTorch engine.

The benefit is using less space on the users disk.

**Comment by frankfliu** [comment]
For of all, to load a native shared library in java, it must be file in the system. So extract to disk is a must have.

skiko is also extract to temp folder, and delete it when JVM exit, see:
https://github.com/JetBrains/skiko/blob/5b5ee682e2a1586ea53cc214960fba280d559ca2/skiko/src/jvmMain/kotlin/org/jetbrains/skiko/Library.kt#L34

Since the DJL native file are huge, we keep them in the cache folder to avoid repeatedly download. There are other desktop application using DJL. Most of them download the native library at runtime. The size of offline distribution binary size is huge (linux/mac/windows X x86_64/aarch64  X cpu/gpu).

**Comment by StefanOltmann** [comment]
Understood, thanks for the pointer.
